name: KomiQ
description: "A Unique Manga Reader with autoscroll & music playing options."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  just_audio_background: ^0.0.1-beta.15
  shared_preferences: ^2.5.3
  just_audio: ^0.9.46
  youtube_explode_dart: ^2.4.0
  webview_flutter: ^4.10.0
  file_picker: ^10.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/